services:
  backend:
    build:
      context: ./backend
    ports:
      - "80:3000"
    networks:
      - app-network
    volumes:
    - .env:/app/.env # Copy the .env file into the container
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8080:3000" 
  #   networks:
  #     - app-network
networks:
  app-network:
    driver: bridge
